# 02 Exercises - Data Types

Here are 10 exercises to help you practice what you've learned about NumPy data types:

**Note**: If any exercises require techniques we haven't covered yet - you should look this up! It's part of the learning process, we need to build the muscle of learning how to do things we haven't seen before.


Remember to check the dtype of the arrays you create using the `dtype` attribute and observe the differences between arrays created with different dtypes.

1. Create a 1D NumPy array containing the numbers 1 to 5 with the default integer dtype.


In [3]:
import numpy as np

In [4]:
arr = np.arange(1, 6)
print(arr)

[1 2 3 4 5]


2. Create the same 1D NumPy array as in exercise 1, but with the `int8` dtype.


In [7]:
arr = np.arange(1, 6, dtype = np.int8)
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int8



3. Create a 2D NumPy array with 2 rows and 3 columns, filled with the value 1.5, using the default floating-point dtype.


In [8]:
arr = np.full((2, 3), 1.5)
print(arr)
print(arr.dtype)

[[1.5 1.5 1.5]
 [1.5 1.5 1.5]]
float64



4. Create the same 2D NumPy array as in exercise 3, but with the `float32` dtype.


In [10]:
arr = np.full((2, 3), 1.5, dtype = np.float32)
print(arr)
print(arr.dtype)

[[1.5 1.5 1.5]
 [1.5 1.5 1.5]]
float32



5. Create a 1D NumPy array containing the numbers 1 to 10 with the default integer dtype. Then, change the dtype to `float64` using the `astype()` method.


In [16]:
arr = np.arange(1, 11)
print(f"{arr}, \n{arr.dtype}")
arrfloat64 = arr.astype(np.float64)
print(f"{arrfloat64}\n{arrfloat64.dtype}")

[ 1  2  3  4  5  6  7  8  9 10], 
int64
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
float64



6. Create a 2D NumPy array with 3 rows and 3 columns, filled with the value 255, using the `uint8` dtype.


In [17]:
arr = np.full((3, 3), 255, dtype = np.uint8)
print(arr)
print(arr.dtype)

[[255 255 255]
 [255 255 255]
 [255 255 255]]
uint8



7. Create a 1D NumPy array containing the numbers 1 to 5 with the default integer dtype. Then, print the dtype of the array.


In [18]:
arr = np.arange(1, 6)
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64



8. Create a 2D NumPy array with 2 rows and 2 columns, filled with the value 1 + 1j, using the `complex128` dtype.


In [21]:
arr = np.full((2, 2), 1 + 1j, dtype = np.complex128)
print(arr)
print(arr.dtype)

[[1.+1.j 1.+1.j]
 [1.+1.j 1.+1.j]]
complex128



9. Create a 1D NumPy array containing the boolean values True, False, True, False, True, using the `bool` dtype.


In [22]:
arr = (np.arange(5) % 2 == 0)
print(arr)
print(arr.dtype)

[ True False  True False  True]
bool


10. Create a 2D NumPy array with 2 rows and 3 columns, filled with the value 10, using the default integer dtype. Then, change the dtype to `uint16` using the `astype()` method.


In [25]:
arr = np.full((2, 3), 10)
print(arr)
print(arr.dtype)
arr = arr.astype(np.uint16)
print(arr)
print(arr.dtype)

[[10 10 10]
 [10 10 10]]
int64
[[10 10 10]
 [10 10 10]]
uint16
