## 04 - NumPy Array Attributes Exercises

**Note**: If any exercises require techniques we haven't covered yet - you should look this up! It's part of the learning process, we need to build the muscle of learning how to do things we haven't seen before.

Don't be shy, ask for help on Discord!

1. Create a 2D NumPy array with 4 rows and 5 columns filled with random integers between 0 and 9. Print the dtype of the array.



In [2]:
import numpy as np

In [5]:
arr = np.random.randint(0, 10, size = (4, 5))
print(arr)
print(arr.dtype)

[[8 8 7 7 5]
 [2 2 7 3 5]
 [8 4 7 5 4]
 [5 0 0 6 5]]
int64



2. Create a 3D NumPy array with 2 matrices of 3 rows and 4 columns filled with the value 3.14. Print the shape of the array.


In [8]:
arr = np.full((3, 4), 3.14)
print(arr)
print(arr.dtype)

[[3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]]
float64



3. Create a 1D NumPy array containing the numbers from 1 to 10. Print the number of dimensions (ndim) of the array.


In [11]:
arr = np.arange(1, 11)
print(arr)
print(arr.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
1



4. Create a 2D NumPy array with 3 rows and 3 columns filled with the value 1. Print the total number of elements (size) in the array.


In [13]:
arr = np.full((3, 3), 1)
print(arr)
print(arr.size)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
9



5. Create a 1D NumPy array containing the numbers from 1 to 5 with the dtype 'int8'. Print the size of each element (itemsize) in the array. Try again with the dtype 'float64'. What do you notice?


In [17]:
arr = np.arange(1, 6, dtype = np.int8)
print(arr)
print(arr.dtype)
print()
arr2= np.arange(1, 6, dtype = np.float64)
print(arr2)
print(arr2.dtype)

[1 2 3 4 5]
int8

[1. 2. 3. 4. 5.]
float64



6. Create a 3D NumPy array with 2 matrices of 2 rows and 3 columns filled with the value 255. Print the total size (nbytes) of the array in bytes.


In [7]:
arr = np.full((2, 2, 3), 255)
print(arr)
print(arr.nbytes)

[[[255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]]]
96



7. Create a 2D NumPy array with 2 rows and 3 columns filled with the values [[1, 2, 3], [4, 5, 6]]. Print the transpose of the array. What is the transpose of a tranpose?


In [10]:
arr = np.arange(1, 7).reshape(2, 3)
print(arr)
print()
print(arr.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]



8. Create a 1D NumPy array containing the numbers from 1 to 9. Reshape the array into a 3x3 matrix and assign it to a new variable. Print the base of the new array.


In [11]:
arr = np.arange(1, 10)
print(arr)
arr1 = arr.reshape(3, 3)
print()
print(arr1)
print(arr1.base)

[1 2 3 4 5 6 7 8 9]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]



9. Create a 2D NumPy array with 3 rows and 4 columns filled with random float numbers between 0 and 1. Print the dtype, shape, and ndim of the array.


In [16]:
arr = np.random.rand(3, 4)
print(arr)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

[[0.99454496 0.18298863 0.87248083 0.4418657 ]
 [0.91892476 0.43835326 0.49306966 0.40122561]
 [0.73773579 0.3006995  0.92452208 0.13308488]]
float64
2
(3, 4)



10. Create a 3D NumPy array with 2 matrices of 2 rows and 2 columns filled with the value 10. Print the size and itemsize of the array.


In [20]:
arr = np.full((2, 2, 2), 10)
print(arr)
print(arr.size)
print(arr.itemsize)

[[[10 10]
  [10 10]]

 [[10 10]
  [10 10]]]
8
8



11. Create a 1D NumPy array containing the numbers from 1 to 6. Reshape the array into a 2x3 matrix and assign it to a new variable. Print the nbytes of both the original and the new array.


In [28]:
arr = np.arange(1, 7)
print(arr)
print()
arr1 = arr.reshape(2, 3)
print(arr1)
print(f"nbytes of arr {arr.nbytes}")
print(f"nbytes of arr1 {arr1.nbytes}")

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]
nbytes of arr 48
nbytes of arr1 48



12. Create a 2D NumPy array with 4 rows and 4 columns filled with the value 1. Use advanced indexing to create a new array containing only the 2nd and 4th rows of the original array. Print the base of the new array. 
 
We have one example of advanced indexing in the material see if you can extrapolate.


In [44]:
arr = np.ones((4, 4))
print(arr)
arr1 = arr[[1 , 3]]
print()
print(arr1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]



13. Create a 1D NumPy array containing the numbers from 1 to 12. Reshape the array into a 3x4 matrix. Print the shape and ndim of the new array.


In [45]:
arr = np.arange(1, 13)
print(arr)
print()
arr1 = arr.reshape(3, 4)
print(arr1)
print()
print(arr1.ndim)
print()
print(arr1.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

2

(3, 4)



14. Create a 2D NumPy array with 3 rows and 3 columns filled with random integers between 1 and 100. Print the dtype, itemsize, and nbytes of the array.


In [50]:
arr = np.random.randint(1, 101, size = (3, 3))
print(arr)

print(arr.itemsize)
print(arr.nbytes)

[[90 50  7]
 [75 37 71]
 [78 96 55]]
8
72



15. Create a 3D NumPy array with 2 matrices of 3 rows and 3 columns filled with the value 5. Transpose the array and print the shape of the transposed array. Can you predict the transpose shape correctly?

In [53]:
arr = np.full((2, 3, 3), 5)
print(arr)
print()
arr1 = arr.T
print(arr1)
print(arr1.shape)

[[[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]]

[[[5 5]
  [5 5]
  [5 5]]

 [[5 5]
  [5 5]
  [5 5]]

 [[5 5]
  [5 5]
  [5 5]]]
(3, 3, 2)
