
# NumPy Exercises for Operations

**Note**: If any exercises require techniques we haven't covered yet - you should look this up! It's part of the learning process, we need to build the muscle of learning how to do things we haven't seen before.

Don't be shy, ask for help on Discord!

1. Create two 1D NumPy arrays with 5 elements each, filled with random integers between 1 and 10. Perform element-wise addition, subtraction, multiplication, and division on these arrays.


In [1]:
import numpy as np

In [43]:
arr = np.random.randint(1, 11, size = 5)
arr1 = np.random.randint(1, 11, size = 5)
print(f"first array\n{arr}\nsecond array\n{arr1}\n")
print(f"Addition by 1 {arr + 1} {arr1 + 1}")
print(f"substraction by 1 {arr - 1} {arr1 - 1}")
print(f"Multiplication by 2 {arr * 2} {arr1 + 2}")
print(f"Division by 2 {arr / 2} {arr1 / 2}")

first array
[1 4 2 8 2]
second array
[10  2  1  6  3]

Addition by 1 [2 5 3 9 3] [11  3  2  7  4]
substraction by 1 [0 3 1 7 1] [9 1 0 5 2]
Multiplication by 2 [ 2  8  4 16  4] [12  4  3  8  5]
Division by 2 [0.5 2.  1.  4.  1. ] [5.  1.  0.5 3.  1.5]



2. Create a 2D NumPy array with 3 rows and 4 columns, filled with random floats between 0 and 1. Multiply each element in the array by 10 and then subtract 5 from each element.


In [51]:
arr = np.random.rand(3, 4)
print(f"Original array \n{arr}\n")
result = arr * 10 - 5
print(f"Transformed array \n{result}")

Original array 
[[0.95107874 0.09170516 0.53754456 0.1358674 ]
 [0.53226325 0.54290823 0.30620604 0.69085023]
 [0.88239029 0.26831645 0.09915956 0.90635723]]

Transformed array 
[[ 4.51078735 -4.08294838  0.37544556 -3.64132601]
 [ 0.32263255  0.4290823  -1.93793956  1.90850233]
 [ 3.82390295 -2.31683554 -4.00840445  4.06357233]]



3. Create two 2D NumPy arrays with 2 rows and 3 columns each, filled with random integers between 1 and 5. Perform matrix multiplication on these arrays using the `@` operator.


In [57]:
arr = np.random.randint(1, 6, size = (2, 3))
arr1 = np.random.randint(1, 6, size = (2, 3))
print(f"First array \n{arr}\n")
print(f"Second array \n{arr1}\n")

result = arr @ arr1.T
print(f"After matrix multiplication \n{result}")

First array 
[[3 5 2]
 [1 5 2]]

Second array 
[[2 4 2]
 [3 1 1]]

After matrix multiplication 
[[30 16]
 [26 10]]



4. Create a 2D NumPy array with 4 rows and 4 columns, filled with random integers between 1 and 10. Calculate the sum, mean, and standard deviation of all elements in the array.


In [59]:
arr = np.random.randint(1, 11, size = (4, 4))
print(f"Original array\n{arr}\n")
total_sum = arr.sum()
mean_val = arr.mean()
std_val = arr.std()

print("Sum of all elements:", total_sum)
print("Mean of all elements:", mean_val)
print("Standard deviation of all elements:", std_val)

Original array
[[ 4  9 10  7]
 [ 2  6  8  7]
 [ 7  6  9  6]
 [ 5  4  2  4]]

Sum of all elements: 96
Mean of all elements: 6.0
Standard deviation of all elements: 2.318404623873926



5. Using the array from exercise 4, calculate the sum, mean, and standard deviation along each row and each column.


In [61]:
print(arr)
row_sum = arr.sum(axis=1)
col_sum = arr.sum(axis=0)

row_mean = arr.mean(axis=1)
col_mean = arr.mean(axis=0)

row_std = arr.std(axis=1)
col_std = arr.std(axis=0)

print("\nRow sums:", row_sum)
print("Column sums:", col_sum)

print("\nRow means:", row_mean)
print("Column means:", col_mean)

print("\nRow stds:", row_std)
print("Column stds:", col_std)

[[ 4  9 10  7]
 [ 2  6  8  7]
 [ 7  6  9  6]
 [ 5  4  2  4]]

Row sums: [30 23 28 15]
Column sums: [18 25 29 24]

Row means: [7.5  5.75 7.   3.75]
Column means: [4.5  6.25 7.25 6.  ]

Row stds: [2.29128785 2.27760839 1.22474487 1.08972474]
Column stds: [1.80277564 1.78535711 3.1124749  1.22474487]



6. Create a 1D NumPy array with 10 elements, filled with random integers between 1 and 100. Apply the following universal functions to the array: square root, natural logarithm, and exponential.


In [67]:
arr = np.random.randint(1, 101, size = (10))
print(f"Original array\n{arr}\n")
sqrt_arr = np.sqrt(arr)        
log_arr = np.log(arr)         
exp_arr = np.exp(arr)                                 
print(f"Square root:\n{sqrt_arr}\n")
print(f"Natural log:\n{log_arr}\n")
print(f"Exponential:\n{exp_arr}\n")

Original array
[81 85 12 50 56 51 88 96 62  8]

Square root:
[9.         9.21954446 3.46410162 7.07106781 7.48331477 7.14142843
 9.38083152 9.79795897 7.87400787 2.82842712]

Natural log:
[4.39444915 4.44265126 2.48490665 3.91202301 4.02535169 3.93182563
 4.47733681 4.56434819 4.12713439 2.07944154]

Exponential:
[1.50609731e+35 8.22301271e+36 1.62754791e+05 5.18470553e+21
 2.09165950e+24 1.40934908e+22 1.65163625e+38 4.92345829e+41
 8.43835667e+26 2.98095799e+03]




7. Create a 2D NumPy array with 3 rows and 3 columns, filled with random floats between -1 and 1. Apply the following universal functions to the array: absolute value, sine, and cosine.


In [69]:
arr = np.random.uniform(-1, 1, size=(3, 3))
print("Original array:\n", arr)

abs_arr = np.abs(arr)     
sin_arr = np.sin(arr)      
cos_arr = np.cos(arr)

print("\nAbsolute value:\n", abs_arr)
print("\nSine:\n", sin_arr)
print("\nCosine:\n", cos_arr)

Original array:
 [[ 0.11204863  0.84645974  0.90586334]
 [ 0.10536885 -0.98571261  0.50406283]
 [-0.96249907  0.22051858  0.66872909]]

Absolute value:
 [[0.11204863 0.84645974 0.90586334]
 [0.10536885 0.98571261 0.50406283]
 [0.96249907 0.22051858 0.66872909]]

Sine:
 [[ 0.11181432  0.74893919  0.78695814]
 [ 0.10517398 -0.83366586  0.48298704]
 [-0.82062228  0.21873568  0.61998932]]

Cosine:
 [[0.99372912 0.66263873 0.61700639]
 [0.99445384 0.55226918 0.8756275 ]
 [0.57147098 0.97578415 0.78461025]]



8. Create two 1D NumPy arrays with 6 elements each, filled with random integers between 1 and 10. Perform element-wise comparison operations on these arrays: greater than, less than, and equal to.


In [75]:
arr = np.random.randint(1, 11, size = 6)
arr1 = np.random.randint(1, 11, size = 6)
print(f"First array\n{arr}\n")
print(f"Second array\n{arr1}\n")
print(f"Greater than (arr > arr1) {arr > arr1}")
print(f"Less than (arr < arr1) {arr < arr1}")
print(f"Equal to (arr = arr1) {arr == arr1}")

First array
[ 9  1  2 10  9  9]

Second array
[8 5 2 6 1 9]

Greater than (arr > arr1) [ True False False  True  True False]
Less than (arr < arr1) [False  True False False False False]
Equal to (arr = arr1) [False False  True False False  True]



9. Create a 2D NumPy array with 5 rows and 5 columns, filled with random integers between 1 and 100. Find the maximum and minimum values in the array along each row and each column.


In [76]:
arr = np.random.randint(1, 101, size = (5, 5))
print("Array:\n", arr, "\n")

print("Maximum along each row:", np.max(arr, axis=1))
print("Minimum along each row:", np.min(arr, axis=1))

print("Maximum along each column:", np.max(arr, axis=0))
print("Minimum along each column:", np.min(arr, axis=0))

Array:
 [[10 42 40 38 22]
 [91 69 54 89  2]
 [13 15 68 91 54]
 [57 33 43 16 72]
 [58 58 93 39 76]] 

Maximum along each row: [42 91 91 72 93]
Minimum along each row: [10  2 13 16 39]
Maximum along each column: [91 69 93 91 76]
Minimum along each column: [10 15 40 16  2]



10. Create a 1D NumPy array with 8 elements, filled with random integers between 1 and 20. Calculate the dot product of this array with itself.


In [80]:
arr = np.random.randint(1 ,20, size = 8)
print("Array\n",arr)
dot_product = np.dot(arr, arr)
print("Dot product of arr with itself:", dot_product)

Array
 [12 18  8 15  4 13  7  5]
Dot product of arr with itself: 1016



11. Create a 2D NumPy array with 4 rows and 4 columns, filled with random floats between 0 and 1. Apply the following universal functions to the array: ceil, floor, and round.


In [89]:
arr = np.random.rand(4, 4)
print("Original array\n",arr)
ceil = np.ceil(arr)
floor = np.floor(arr)
round_arr = np.round(arr)

print(f"\nArray ceiling\n{ceil}\n")
print(f"Array floor\n{floor}\n")
print(f"Array round\n{round_arr}")

Original array
 [[0.48560092 0.74913636 0.38807745 0.9416981 ]
 [0.02061195 0.43207567 0.50192966 0.3333049 ]
 [0.64212597 0.21459321 0.01591913 0.17970813]
 [0.51097485 0.02902659 0.58767206 0.71432231]]

Array ceiling
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array floor
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array round
[[0. 1. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 1. 1.]]



12. Create two 2D NumPy arrays with 3 rows and 3 columns each, filled with random integers between 1 and 10. Perform element-wise addition, subtraction, multiplication, and division on these arrays.


In [97]:
arr = np.random.randint(1, 10, size = (3, 3))
arr1 = np.random.randint(1, 10, size = (3, 3))
print(f"First array\n{arr}\n")
print(f"Second array\n{arr1}\n")
print(f"Addition\n{arr + arr1}\n")
print(f"Substraction\n{arr - arr1}\n")
print(f"Multiplication\n{arr * arr1}\n")
print(f"Division\n{arr / arr1}\n")

First array
[[8 3 7]
 [2 7 7]
 [7 1 5]]

Second array
[[7 3 5]
 [3 5 2]
 [3 7 8]]

Addition
[[15  6 12]
 [ 5 12  9]
 [10  8 13]]

Substraction
[[ 1  0  2]
 [-1  2  5]
 [ 4 -6 -3]]

Multiplication
[[56  9 35]
 [ 6 35 14]
 [21  7 40]]

Division
[[1.14285714 1.         1.4       ]
 [0.66666667 1.4        3.5       ]
 [2.33333333 0.14285714 0.625     ]]




13. Create a 1D NumPy array with 7 elements, filled with random integers between 1 and 100. Calculate the sum of the array using a Python loop and compare the execution time with the NumPy `sum()` function using the `%%timeit` magic command.


In [16]:
arr = np.random.randint(1, 101, size = 7)
print("Array\n",arr)   

Array
 [ 7 56 48 82 89 52 47]


In [23]:
def python_sum(arr):
    total = 0
    for num in arr:
        total += num
    return total 
    
print("Python loop sum:", python_sum(arr))
print("NumPy sum:", np.sum(arr))

Python loop sum: 381
NumPy sum: 381


In [24]:
%%timeit
python_sum(arr)

1.9 μs ± 307 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [25]:
%%timeit
jup_sum = np.sum(arr)

3.44 μs ± 568 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)



14. Create a 2D NumPy array with 6 rows and 6 columns, filled with random floats between -10 and 10. Apply the following universal functions to the array: hyperbolic sine, hyperbolic cosine, and hyperbolic tangent. (Practice those look up skills!)


In [28]:
arr = np.random.uniform(-10, 10, size = (6, 6))
print("Array\n",arr)
print()
sinh_arr = np.sinh(arr)
cosh_arr = np.cosh(arr)
tanh_arr = np.tanh(arr)

print("Hyperbolic Sine (sinh):\n", sinh_arr, "\n")
print("Hyperbolic Cosine (cosh):\n", cosh_arr, "\n")
print("Hyperbolic Tangent (tanh):\n", tanh_arr)

Array
 [[-1.62250331  1.07576855 -5.46555065  4.57397116 -5.96450488 -4.3099814 ]
 [ 7.40249269 -5.60580194 -9.25508211  9.23910726  0.83113381 -3.92338912]
 [ 9.13911607  2.24511737 -6.71128662 -2.1583365  -6.30180686 -0.4201544 ]
 [-3.48225368 -1.92935636 -2.76162164 -7.80066005  0.88634115  5.66393276]
 [-6.59384033  8.29990349 -7.81581839  9.76250331  6.9935847  -6.59312634]
 [ 2.38147752 -7.88723201  6.33119876 -0.43458526  0.82383934  0.02015732]]

Hyperbolic Sine (sinh):
 [[-2.43417584e+00  1.29560502e+00 -1.18200884e+02  4.84589735e+01
  -1.94678817e+02 -3.72128351e+01]
 [ 8.20033450e+02 -1.35998145e+02 -5.22878866e+03  5.14592318e+03
   9.30182612e-01 -2.52758870e+01]
 [ 4.65626490e+03  4.66780429e+00 -4.10812934e+02 -4.27060406e+00
  -2.72777465e+02 -4.32625590e-01]
 [-1.62511101e+01 -3.36991782e+00 -7.88114807e+00 -1.22110651e+03
   1.00703757e+00  1.44138342e+02]
 [-3.65289896e+02  2.01174191e+03 -1.23975747e+03  8.68502998e+03
   5.44809763e+02 -3.65029174e+02]
 [ 5.364232


15. Create two 1D NumPy arrays with 100 elements each, filled with random floats between 0 and 1. Perform element-wise multiplication on these arrays using a Python loop and compare the execution time with the NumPy element-wise multiplication using the `%%timeit` magic command.

In [29]:
arr1 = np.random.rand(100)
arr2 = np.random.rand(100)
print("First array\n",arr1)
print("Second array\n",arr2)

First array
 [0.90191069 0.07193468 0.68673811 0.37969386 0.16250059 0.83898806
 0.74515374 0.22598441 0.08692935 0.95463273 0.02033233 0.3375339
 0.00857471 0.36761695 0.19720209 0.80173072 0.14690297 0.86964697
 0.90614342 0.58892834 0.95537156 0.18488608 0.79899513 0.24914494
 0.68888879 0.98973553 0.44633052 0.98917185 0.88422888 0.52200117
 0.17392614 0.8270186  0.18949157 0.01173456 0.18078014 0.36021978
 0.4414103  0.66773828 0.42206785 0.42555499 0.17634271 0.13166128
 0.59186837 0.36694653 0.15759207 0.55827809 0.42112313 0.22668158
 0.24617068 0.89143411 0.80608537 0.13269436 0.01421151 0.029809
 0.87934592 0.5774581  0.70599343 0.91404806 0.70345151 0.30422184
 0.17322469 0.20880628 0.78695812 0.03626892 0.78835207 0.58713207
 0.31991728 0.65941071 0.74999513 0.49709204 0.73421208 0.4065899
 0.13212434 0.13176893 0.89463621 0.17056896 0.6529048  0.81711689
 0.50470894 0.72621839 0.85712648 0.01280172 0.66687823 0.64289914
 0.11063922 0.47171203 0.19242686 0.27366458 0.769285

In [30]:
def python_multiply(a, b):
    result = []
    for i in range(len(a)):
        result.append(a[i] * b[i])
    return result

In [31]:
%%timeit
python_multiply(arr1, arr2)

37.1 μs ± 3.52 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [32]:
print(python_multiply(arr1, arr2))

[np.float64(0.41035676402143934), np.float64(0.02404076073290068), np.float64(0.6830289045170138), np.float64(0.32015204795325625), np.float64(4.20070158440868e-05), np.float64(0.8013149627636263), np.float64(0.11070351296173918), np.float64(0.21611354971340183), np.float64(0.0490199757517101), np.float64(0.7011599482546577), np.float64(0.006048890215125157), np.float64(0.06333988865232734), np.float64(0.0028202456198387566), np.float64(0.0739896089031676), np.float64(0.010202442378468391), np.float64(0.20539632833798852), np.float64(0.00889265084576973), np.float64(0.14613350291183644), np.float64(0.09700769264727412), np.float64(0.3418996288378308), np.float64(0.7075947516909844), np.float64(0.0881105801154061), np.float64(0.607999960689789), np.float64(0.016073978749972916), np.float64(0.21036156109645937), np.float64(0.9269123738965163), np.float64(0.42087582802238516), np.float64(0.6073400765448786), np.float64(0.27429155968291924), np.float64(0.5175125424817314), np.float64(0.102

In [33]:
%%timeit
arr1 * arr2

1.14 μs ± 267 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [34]:
print(arr1 * arr2)

[4.10356764e-01 2.40407607e-02 6.83028905e-01 3.20152048e-01
 4.20070158e-05 8.01314963e-01 1.10703513e-01 2.16113550e-01
 4.90199758e-02 7.01159948e-01 6.04889022e-03 6.33398887e-02
 2.82024562e-03 7.39896089e-02 1.02024424e-02 2.05396328e-01
 8.89265085e-03 1.46133503e-01 9.70076926e-02 3.41899629e-01
 7.07594752e-01 8.81105801e-02 6.07999961e-01 1.60739787e-02
 2.10361561e-01 9.26912374e-01 4.20875828e-01 6.07340077e-01
 2.74291560e-01 5.17512542e-01 1.02485954e-01 6.09127125e-01
 1.40226760e-02 3.53889005e-03 1.49276589e-01 3.14771422e-01
 2.10635146e-01 3.12575839e-01 1.86234402e-02 1.56681556e-01
 5.12136922e-02 2.57590179e-02 1.20933088e-01 5.89385734e-02
 9.69039596e-02 3.23339239e-03 2.07355093e-01 2.76210795e-02
 2.39727718e-01 2.91306092e-01 1.17207267e-01 1.03193370e-01
 1.08866351e-02 2.52356427e-02 3.26682216e-01 9.11152400e-02
 1.84254966e-01 4.47292161e-02 6.23644383e-01 2.69813430e-01
 1.19800787e-01 4.29035840e-02 5.53920354e-01 2.48096450e-02
 6.07459541e-01 3.724051