# 06 - NumPy Slicing Exercises

**Note**: If any exercises require techniques we haven't covered yet - you should look this up! It's part of the learning process, we need to build the muscle of learning how to do things we haven't seen before.

Don't be shy, ask for help on Discord!

1. Create a 1D NumPy array with 10 elements and print the 5th element.


In [1]:
import numpy as np

In [4]:
arr1 = np.arange(10)
print(arr1[4])

4



2. Create a 1D NumPy array with 10 elements and print the last 3 elements using negative indexing.


In [7]:
arr1 = np.arange(10)
print(arr1[-3:])

[7 8 9]



3. Create a 1D NumPy array with 10 elements and print every other element starting from the 2nd element.


In [9]:
arr1 = np.arange(10)
print(arr1[1::2])

[1 3 5 7 9]



4. Create a 2D NumPy array with 4 rows and 5 columns. Print the element at the 3rd row and 4th column.


In [18]:
arr1 = np.arange(1, 21).reshape(4, 5)
print(arr1)
print()
print(arr1[2,3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

14



5. Create a 2D NumPy array with 4 rows and 5 columns. Print the 2nd and 3rd rows.


In [21]:
arr1 = np.arange(1, 21).reshape(4 ,5)
print(arr1)
print()
print(arr1[1:3:,])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 6  7  8  9 10]
 [11 12 13 14 15]]



6. Create a 2D NumPy array with 4 rows and 5 columns. Print the 2nd and 4th columns.


In [29]:
arr1 = np.arange(1, 21).reshape(4, 5)
print(arr1)
print()
print(arr1[:, 1:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]



7. Create a 2D NumPy array with 4 rows and 5 columns. Print a subarray consisting of the first 2 rows and the last 2 columns.


In [32]:
arr1 = np.random.randint(1, 21, size = (4, 5))
print(arr1)
print()
arr2 = arr1[:2, -2:]
print(arr2)

[[16 14  7 18 16]
 [12 10 14 14 10]
 [18 11 11  7 11]
 [15 13  3 12 19]]

[[18 16]
 [14 10]]



8. Create a 1D NumPy array with 10 elements. Assign the value 99 to the 3rd and 4th elements.



9. Create a 2D NumPy array with 4 rows and 5 columns. Assign the value 0 to the elements in the 2nd and 3rd columns.


In [39]:
arr1 = np.random.randint(1, 101, size =(4, 5))
print(arr1)
print()
arr1[:,1:3] = 0
print(arr1)

[[10 72 68  5  8]
 [79 32 68 65 87]
 [89 93 36 59 86]
 [56 44 61 50 27]]

[[10  0  0  5  8]
 [79  0  0 65 87]
 [89  0  0 59 86]
 [56  0  0 50 27]]



10. Create a 1D NumPy array with 15 random integers between 1 and 100. Use boolean indexing to print all the elements that are greater than 50.


In [43]:
arr1 = np.random.randint(1, 101, size = 15)
print(arr1)
print()

print(arr1[arr1 > 50])

[ 2 66 33 66 97 81  1 35 73 47 44  5 99 57 17]

[66 66 97 81 73 99 57]



11. Create a 2D NumPy array with 5 rows and 5 columns filled with random integers between 1 and 100. Use boolean indexing to print all the elements that are divisible by 3.


In [47]:
arr1 = np.random.randint(1, 101, size = (5, 5))
print(arr1)
print()
print("Elements divisible by 3: ",arr1[arr1 % 3 == 0])

[[71 10 71  6  5]
 [75 83 59 82 21]
 [90  6 38 78 93]
 [55 80  9 34 43]
 [25 98 36 98 51]]

Elements divisible by 3:  [ 6 75 21 90  6 78 93  9 36 51]



12. Create two 1D NumPy arrays with 10 random integers between 1 and 100. Use boolean indexing to print the elements from the first array that are greater than the corresponding elements in the second array.


In [49]:
arr1 = np.random.randint(1, 101, size = 10)
print(arr1)
print()
arr2= np.random.randint(1, 101, size = 10)
print(arr2)
print()
print(arr1[arr1 > arr2])

[15 33 34 13 35 61 62 81 58 47]

[13 36 53 32 46 77 82 74 90 32]

[15 81 47]



13. Create a 2D NumPy array with 6 rows and 6 columns filled with random integers between 1 and 100. Use boolean indexing to print the rows where the sum of the elements in the row is greater than 300.


In [57]:
arr1 = np.random.randint(1, 101, size = (6, 6))
print(arr1)
print()
row_sum = arr1.sum(axis = 1)
print(arr1[row_sum > 300])

[[ 4 42 46 29 39 35]
 [25 51 43 14 60 85]
 [48 39 34 33  2 78]
 [64 91 18 30 70 10]
 [73 40 73 14 84 34]
 [44  2 33 70 15 97]]

[[73 40 73 14 84 34]]



14. Create a 1D NumPy array with 20 random integers between 1 and 100. Use integer array indexing to print the elements at indices 2, 5, and 9.


In [63]:
arr1 = np.random.randint(1, 101, size = 20)
print(arr1)
print(arr1[[2, 5, 9]])

[27 88 13 13 88 25 59  3  1 84 93 54 64 31 59 50  1 18 12 57]
[13 25 84]



15. Create a 2D NumPy array with 5 rows and 5 columns filled with random integers between 1 and 100. Use integer array indexing to print the elements at (1, 1), (2, 3), and (4, 4) in a single array.

In [67]:
arr1 = np.random.randint(1, 101, size = (5, 5))
print(arr1)
print(arr1[[1, 2, 4], [1, 3, 4]])

[[11 82 41 47  3]
 [13 75 16 17 67]
 [81 27 74 63 99]
 [33 59 19 78  9]
 [75  8 22 97 36]]
[75 63 36]
