# 07 Views and Copies in Numpy Exercises

**Note**: If any exercises require techniques we haven't covered yet - you should look this up! It's part of the learning process, we need to build the muscle of learning how to do things we haven't seen before.

Don't be shy, ask for help on Discord!

You don't need to do all these (it's a lot!). As soon as you get the gist, feel free to move on.

1. Create a 1D NumPy array with 10 elements. Create a view of the first 5 elements and modify the 3rd element of the view. Check if the original array has been modified.


In [1]:
import numpy as np

In [3]:
arr1 = np.arange(10)
print(f"Original array\n{arr1}\n")
view = arr1[:5]
print(f"View of first 5 elements\n{view}\n")
view[2] = 20
print(f"VIew after modification\n{view}\n")
print(f"Array  after modification\n{arr1}")

Original array
[0 1 2 3 4 5 6 7 8 9]

View of first 5 elements
[0 1 2 3 4]

VIew after modification
[ 0  1 20  3  4]

Array  after modification
[ 0  1 20  3  4  5  6  7  8  9]



2. Create a 1D NumPy array with 10 elements. Create a copy of the first 5 elements and modify the 3rd element of the copy. Check if the original array has been modified.


In [6]:
arr1 = np.arange(10)
print(f"Original array\n{arr1}\n")
arr2 = arr1[:5].copy()
print(f"Array copy\n{arr2}\n")
arr2[2] = 99
print(f"first array after modification of copy\n{arr1}\n")
print(f"Copy after modification\n{arr2}\n")

Original array
[0 1 2 3 4 5 6 7 8 9]

Array copy
[0 1 2 3 4]

first array after modification of copy
[0 1 2 3 4 5 6 7 8 9]

Copy after modification
[ 0  1 99  3  4]




3. Create a 2D NumPy array with 4 rows and 5 columns. Create a view of the first 2 rows and modify the element at (1, 1). Check if the original array has been modified.


In [9]:
arr1 = np.arange(1, 21).reshape(4, 5)
print(f"Original array\n{arr1}\n")
view = arr1[:2,]
print(f"View of first two rows\n{view}\n")
view[1, 1] = 99
print(f"View after modification\n{view}\n")
print(f"Array after modification of view\n{arr1}")

Original array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

View of first two rows
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

View after modification
[[ 1  2  3  4  5]
 [ 6 99  8  9 10]]

Array after modification of view
[[ 1  2  3  4  5]
 [ 6 99  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]



4. Create a 2D NumPy array with 4 rows and 5 columns. Create a copy of the first 2 rows and modify the element at (1, 1). Check if the original array has been modified.


In [12]:
arr1 = np.arange(1, 21).reshape(4, 5)
print(f"Original array\n{arr1}\n")
copy = arr1[:2,].copy()
print(f"Copy of the array\n{copy}\n")
copy[1,1] = 999
print(f"Copy after modification\n{copy}\n")
print(f"Array after modification of copy\n{arr1}")

Original array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Copy of the array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Copy after modification
[[  1   2   3   4   5]
 [  6 999   8   9  10]]

Array after modification of copy
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]



5. Create a 1D NumPy array with 10 elements. Create a variable using boolean indexing (e.g., `arr[arr > 5]`) and modify the first element of the variable. Check if the original array has been modified.


In [16]:
arr1 = np.arange(10)
print(f"Original array\n{arr1}\n")
arr2 = arr1[arr1 > 5]
print(arr2)
print()
arr2[0] = 999
print(arr1)
print()
print(arr2)

Original array
[0 1 2 3 4 5 6 7 8 9]

[6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]

[999   7   8   9]



6. Create a 1D NumPy array with 10 elements. Create a variable using boolean indexing with `copy()` (e.g., `arr[arr > 5].copy()`) and modify the first element of the variable. Check if the original array has been modified.


In [21]:
arr1 = np.arange(10)
print(arr1)
copy = arr1[arr1 > 4]
print()
print(copy)
copy[0] = 99
print()
print(copy)
print()
print(arr1)

[0 1 2 3 4 5 6 7 8 9]

[5 6 7 8 9]

[99  6  7  8  9]

[0 1 2 3 4 5 6 7 8 9]



7. Create a 2D NumPy array with 5 rows and 5 columns. Create a variable using integer array indexing (e.g., `arr[[1, 2], [3, 4]]`) and modify the first element of the variable. Check if the original array has been modified.


In [24]:
arr1= np.arange(1, 26).reshape(5, 5)
print(arr1)
print()
arr2 = arr1[[1,3],[2,4]]
print(arr2)
arr2[0] = 99
print()
print(arr2)
print()
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[ 8 20]

[99 20]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]



8. Create a 2D NumPy array with 5 rows and 5 columns. Create a variable using integer array indexing (e.g., `arr[[1, 2], [3, 4]].copy()`) and modify the first element of the variable. Check if the original array has been modified.


In [25]:
arr1 = np.arange(1, 26).reshape(5, 5)
arr2 = arr1[[1,2],[3,4]]
print(arr1)
print()
print(arr2)
print()
arr2[0] = 99
print(arr1)
print()
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[ 9 15]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[99 15]



9. Create a 1D NumPy array with 12 elements. Reshape the array into a 3x4 matrix. Create a view of the first row and modify the 2nd element of the view. Check if the original array has been modified.


In [33]:
arr = np.arange(12)
print(arr)
print()
matrix = arr.reshape(3, 4)
print(matrix)
print()
row = matrix[0]
print(row)
print()
row[1] = 99
print(row)
print(0)
print()
print(matrix)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[0 1 2 3]

[ 0 99  2  3]
0

[[ 0 99  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0 99  2  3  4  5  6  7  8  9 10 11]



10. Create a 1D NumPy array with 12 elements. Reshape the array into a 3x4 matrix. Create a copy of the first row using `arr[0].copy()` and modify the 2nd element of the copy. Check if the original array has been modified.


In [39]:
arr = np.arange(12)
print(arr)
print()
matrix = arr.reshape(3, 4)
print(matrix)
copy = matrix[0].copy()
print()
print(copy)
copy[1] = 99
print()
print(copy)
print()
print(matrix)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[0 1 2 3]

[ 0 99  2  3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]



11. Create a 2D NumPy array with 6 rows and 6 columns. Create a view of every other row starting from the first row and modify the element at (1, 1). Check if the original array has been modified.


In [51]:
arr1 = np.arange(1, 37).reshape(6, 6)
print("Original array:\n", arr1)

view = arr1[::2]
print("\nView (every other row):\n", view)

view[1, 1] = 999
print("\nView after modification:\n", view)

print("\nOriginal array after modification:\n", arr1)


Original array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

View (every other row):
 [[ 1  2  3  4  5  6]
 [13 14 15 16 17 18]
 [25 26 27 28 29 30]]

View after modification:
 [[  1   2   3   4   5   6]
 [ 13 999  15  16  17  18]
 [ 25  26  27  28  29  30]]

Original array after modification:
 [[  1   2   3   4   5   6]
 [  7   8   9  10  11  12]
 [ 13 999  15  16  17  18]
 [ 19  20  21  22  23  24]
 [ 25  26  27  28  29  30]
 [ 31  32  33  34  35  36]]



12. Create a 2D NumPy array with 6 rows and 6 columns. Create a copy of every other row starting from the first row and modify the element at (1, 1). Check if the original array has been modified.


In [56]:
arr = np.arange(1, 37).reshape(6, 6)
print(arr)
copy = arr[::2]
print()
print(copy)
copy[1, 1] = 999
print()
print(copy)
print()
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

[[ 1  2  3  4  5  6]
 [13 14 15 16 17 18]
 [25 26 27 28 29 30]]

[[  1   2   3   4   5   6]
 [ 13 999  15  16  17  18]
 [ 25  26  27  28  29  30]]

[[  1   2   3   4   5   6]
 [  7   8   9  10  11  12]
 [ 13 999  15  16  17  18]
 [ 19  20  21  22  23  24]
 [ 25  26  27  28  29  30]
 [ 31  32  33  34  35  36]]



13. Create a 2D NumPy array with 4 rows and 5 columns. Use boolean indexing to create a view of the elements greater than 10 and modify the first element of the view. Check if the original array has been modified.


In [59]:
arr = np.arange(1, 21).reshape(4, 5)
print(arr)
view = arr[arr > 10]
print()
print(view)
view[0] = 999
print()
print(view)
print()
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[11 12 13 14 15 16 17 18 19 20]

[999  12  13  14  15  16  17  18  19  20]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]



14. Create a 2D NumPy array with 4 rows and 5 columns. Use boolean indexing to create a copy of the elements greater than 10 and modify the first element of the copy. Check if the original array has been modified.


In [62]:
arr = np.arange(1, 21).reshape(4, 5)
print(arr)
print()
copy = arr[arr > 10].copy()
print(copy)
print()
copy[0] = 999
print(copy)
print()
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[11 12 13 14 15 16 17 18 19 20]

[999  12  13  14  15  16  17  18  19  20]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]



15. Create a 1D NumPy array with 15 elements. Create a view of the array using slicing and assign it to a new variable. Modify the first element of the view and check if the `.base` attribute of the view points to the original array.

In [69]:
arr = np.arange(1, 16)
print(arr)
view = arr[3:7]
print()
print(view)
view[0] = 999
print()
print(view) 
print()
print(arr)
print("\nDoes view.base point to original array?", view.base is arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

[4 5 6 7]

[999   5   6   7]

[  1   2   3 999   5   6   7   8   9  10  11  12  13  14  15]

Does view.base point to original array? True
