# 08 Exercises: Manipulating Arrays in NumPy
**Note**: If any exercises require techniques we haven't covered yet - you should look this up! It's part of the learning process, we need to build the muscle of learning how to do things we haven't seen before.

Don't be shy, ask for help on Discord!


1. Create a 1D NumPy array with 12 elements and reshape it into a 3x4 matrix.


In [1]:
import numpy as np

In [5]:
arr1 = np.arange(12)
print(arr1)
arr1 = arr1.reshape(3, 4)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



2. Create a 1D NumPy array with 20 elements and reshape it into a 4x5 matrix.


In [6]:
arr1 = np.arange(1, 21).reshape(4, 5)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]



3. Create a 1D NumPy array with 30 elements and reshape it into a 3D array with dimensions 2x3x5.


In [7]:
arr1 = np.arange(1, 31).reshape(2, 3, 5)
print(arr1)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]



4. Create a 2D NumPy array with dimensions 4x6 and flatten it into a 1D array using `flatten()`.


In [10]:
arr1 = np.arange(1, 25).reshape(4, 6)
print(arr1)
print()
flat = arr1.flatten()
print(flat)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]



5. Create a 2D NumPy array with dimensions 5x5 and flatten it into a 1D array using `ravel()`.


In [12]:
arr1 = np.arange(1, 26).reshape(5, 5)
print(arr1)
print()
flat = arr1.ravel()
print(flat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]



6. Create a 3D NumPy array with dimensions 2x3x4 and flatten it into a 1D array using `reshape(-1)`.


In [14]:
arr1 = np.arange(1, 25).reshape(2, 3, 4)
print(arr1)
flat = arr1.reshape(-1)
print()
print(flat)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]



7. Create a 1D NumPy array with 10 elements and add a new axis to create a column vector using `np.newaxis`.


In [20]:
arr1 = np.arange(10)
print(arr1)
print()
arr2 = arr1[:,np.newaxis]
print(arr2)

[0 1 2 3 4 5 6 7 8 9]

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]



8. Create a 1D NumPy array with 10 elements and add a new axis to create a row vector using `np.expand_dims`.


In [25]:
arr1 = np.arange(10)
print(arr1)
print(arr1.shape)
arr2 = np.expand_dims(arr1, axis = 0)
print(arr2)
print(arr2.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)



9. Create a 2D NumPy array with dimensions 3x4 and add a new axis to create a 3D array with dimensions 1x3x4 using `np.newaxis`.


In [7]:
arr = np.arange(1, 13).reshape(3, 4)
print(f"Original array\n{arr}\n\nShape: {arr.shape}\n")
arr1 = arr[np.newaxis,:,:]
print(f"3D array\n{arr1}\n\nShape: {arr1.shape}")

Original array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape: (3, 4)

3D array
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]

Shape: (1, 3, 4)



10. Create two 1D NumPy arrays with 5 elements each and stack them vertically using `np.vstack()`.


In [13]:
arr1 = np.arange(1, 6)
arr2 = np.arange(6, 11)
print(f"First aray\n{arr1}\n\nSecond array\n{arr2}\n")
arr3 = np.vstack((arr1, arr2))
print(f"Stacked array\n{arr3}\nShape: {arr3.shape}")

First aray
[1 2 3 4 5]

Second array
[ 6  7  8  9 10]

Stacked array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape: (2, 5)



11. Create two 1D NumPy arrays with 5 elements each and stack them horizontally using `np.hstack()`.


In [14]:
arr1 = np.arange(1, 6)
arr2 = np.arange(6, 11)
print(f"First aray\n{arr1}\n\nSecond array\n{arr2}\n")
arr3 = np.hstack((arr1, arr2))
print(f"Stacked array\n{arr3}\nShape: {arr3.shape}")

First aray
[1 2 3 4 5]

Second array
[ 6  7  8  9 10]

Stacked array
[ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)



12. Create two 2D NumPy arrays with dimensions 2x3 and concatenate them vertically using `np.concatenate()`.


In [16]:
arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.arange(7, 13).reshape(2, 3)
print(f"First aray\n{arr1}\n\nSecond array\n{arr2}\n")
arr3 = np.concatenate((arr1, arr2), axis = 0)
print(f"Stacked array\n{arr3}\nShape: {arr3.shape}")

First aray
[[1 2 3]
 [4 5 6]]

Second array
[[ 7  8  9]
 [10 11 12]]

Stacked array
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)



13. Create two 2D NumPy arrays with dimensions 2x3 and concatenate them horizontally using `np.concatenate()`.


In [17]:
arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.arange(7, 13).reshape(2, 3)
print(f"First aray\n{arr1}\n\nSecond array\n{arr2}\n")
arr3 = np.concatenate((arr1, arr2), axis = 1)
print(f"Stacked array\n{arr3}\nShape: {arr3.shape}")

First aray
[[1 2 3]
 [4 5 6]]

Second array
[[ 7  8  9]
 [10 11 12]]

Stacked array
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Shape: (2, 6)



14. Create a 3D NumPy array with dimensions 2x3x4 and remove all the single-dimensional entries using `np.squeeze()`.


In [19]:
arr1 = np.arange(1, 25).reshape(2, 3, 4)
print(f"Original array\n{arr1}\n\nShape: {arr1.shape}\n")
arr2 = np.squeeze(arr1)
print(f"Squeezed array\n{arr2}\n\nShape: {arr2.shape}")

Original array
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Shape: (2, 3, 4)

Squeezed array
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Shape: (2, 3, 4)



15. Create a 2D NumPy array with dimensions 4x4 and reshape it into a 1D array. Then, add two new axes to create a 16x1x1 array using `np.expand_dims()`.

In [33]:
arr1 = np.arange(1, 17).reshape(4, 4)
print(f"Original array\n{arr1}\n\nShape: {arr1.shape}\n")
arr2 = arr1.reshape(-1)
print(f"Squeezed array\n{arr2}\n\nShape: {arr2.shape}")
arr3 = np.expand_dims(arr2, axis = (2,1))
print(f"Expanded array\n{arr3}\n\nShape: {arr3.shape}")

Original array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Shape: (4, 4)

Squeezed array
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]

Shape: (16,)
Expanded array
[[[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]

 [[12]]

 [[13]]

 [[14]]

 [[15]]

 [[16]]]

Shape: (16, 1, 1)
