# 09 Exercises: Sorting
**Note**: If any exercises require techniques we haven't covered yet - you should look this up! It's part of the learning process, we need to build the muscle of learning how to do things we haven't seen before.

Don't be shy, ask for help on Discord!

Remember to print the original array and the sorted array (or indices) for each exercise to check your results.


1. Create a 1D NumPy array with 10 random integers between 1 and 100. Sort the array in ascending order using `np.sort()`.


In [1]:
import numpy as np

In [4]:
arr1 = np.random.randint(1, 101, size = 10)
print(f"Original array\n{arr1}\n")
arr2 = np.sort(arr1)
print(f"Sorted array\n{arr2}")

Original array
[16 97 24 20 89 51 67  6 77 15]

Sorted array
[ 6 15 16 20 24 51 67 77 89 97]



2. Create a 1D NumPy array with 10 random integers between 1 and 100. Sort the array in descending order using `np.sort()` and the `[::-1]` slicing technique.


In [13]:
arr1 = np.random.randint(1, 101, size = 10)
print(f"Original array\n{arr1}\n")
arr2 = np.sort(arr1)[::-1]
print(f"Sorted array\n{arr2}")

Original array
[11 30 10 43 47 74 44 44 38 64]

Sorted array
[74 64 47 44 44 43 38 30 11 10]



3. Create a 1D NumPy array with 10 random integers between 1 and 100. Use `np.argsort()` to get the indices that would sort the array in ascending order.


In [14]:
arr1 = np.random.randint(1, 101, size = 10)
print(f"Original array\n{arr1}\n")
arr2 = np.argsort(arr1)
print(f"Indices that would sort the array in ascening order\n{arr2}")

Original array
[82  8 12  7 85 60 46 90 42 76]

Indices that would sort the array in ascening order
[3 1 2 8 6 5 9 0 4 7]



4. Create a 1D NumPy array with 10 random integers between 1 and 100. Sort the array in-place using the `sort()` method.


In [15]:
arr1 = np.random.randint(1, 101, size = 10)
print(f"Original array\n{arr1}\n")
arr1.sort()
print(f"Sorted array\n{arr1}")

Original array
[45 27 80 98 86 11 48 84 68 28]

Sorted array
[11 27 28 45 48 68 80 84 86 98]



5. Create a 2D NumPy array with dimensions 3x4 filled with random integers between 1 and 100. Sort the array along the first axis (rows) using `np.sort()`.


In [17]:
arr1 = np.random.randint(1, 101, size = (3, 4))
print(f"Original array\n{arr1}\n")
arr2 = np.sort(arr1, axis = 0)
print(f"Sorted array along the first axis\n{arr2}")

Original array
[[31 35 89 11]
 [64 23 33 82]
 [56 31 54 86]]

Sorted array along first axis
[[31 23 33 11]
 [56 31 54 82]
 [64 35 89 86]]



6. Create a 2D NumPy array with dimensions 4x5 filled with random integers between 1 and 100. Sort the array along the second axis (columns) using `np.sort()`.


In [19]:
arr1 = np.random.randint(1 ,101 ,size = (4, 5))
print(f"Original array\n{arr1}\n")
arr2 = np.sort(arr1, axis = 1)
print(f"Sorted array along the second axis\n{arr2}")

Original array
[[ 4 97 75 77  6]
 [59 88 30 44 33]
 [86 32 59 70 61]
 [10 83 65 13 64]]

Sorted array along the second axis
[[ 4  6 75 77 97]
 [30 33 44 59 88]
 [32 59 61 70 86]
 [10 13 64 65 83]]



7. Create a 2D NumPy array with dimensions 5x5 filled with random integers between 1 and 100. Use `np.argsort()` to get the indices that would sort the array along the first axis (rows).


In [20]:
arr1 = np.random.randint(1, 101, size = (5, 5))
print(f"Original array\n{arr1}\n")
arr2 = np.argsort(arr1, axis = 0)
print(f"Indices that would sort the array along the first axis\n{arr2}")

Original array
[[ 56  82  46   6  99]
 [ 72  13  71  77  97]
 [ 11  44  50  61  10]
 [ 29  72  32  26 100]
 [ 30   6  75  35  47]]

Indices that would sort the array along the first axis
[[2 4 3 0 2]
 [3 1 0 3 4]
 [4 2 2 4 1]
 [0 3 1 2 0]
 [1 0 4 1 3]]



8. Create a 2D NumPy array with dimensions 4x6 filled with random integers between 1 and 100. Use `np.argsort()` to get the indices that would sort the array along the second axis (columns).


In [21]:
arr1 = np.random.randint(1, 101, size = (4, 6))
print(f"Original array\n{arr1}\n")
arr2 = np.argsort(arr1, axis = 1)
print(f"Indices that would sort the array along the second axis\n{arr2}")

Original array
[[18 60 65 13  8 47]
 [69 72 67 65 89 64]
 [91 78 72 80 42 41]
 [19 53 35  1 16  5]]

Indices that would sort the array along the second axis
[[4 3 0 5 1 2]
 [5 3 2 0 1 4]
 [5 4 2 1 3 0]
 [3 5 4 0 2 1]]



9. Create a 2D NumPy array with dimensions 3x3 filled with random integers between 1 and 100. Sort each row of the array in-place using the `sort()` method.


In [27]:
arr1 = np.random.randint(1, 101, size = (3, 3))
print(f"Original array\n{arr1}\n")
arr1.sort(axis = 1)
print(f"Array after in-place row-wise sort\n{arr1}")

Original array
[[ 24  76 100]
 [ 65  91  19]
 [ 13  19   5]]

Array after in-place row-wise sort
[[ 24  76 100]
 [ 19  65  91]
 [  5  13  19]]



10. Create a 2D NumPy array with dimensions 5x2 filled with random integers between 1 and 100. Sort each column of the array in-place using the `sort()` method and the `axis` parameter.



In [29]:
arr1 = np.random.randint(1, 101, size = (5, 2))
print(f"Original array\n{arr1}\n")
arr1.sort(axis = 0)
print(f"Array after in-place column-wise sort\n{arr1}")

Original array
[[ 8 65]
 [69 84]
 [58 75]
 [ 7 85]
 [24 12]]

Array after in-place column-wise sort
[[ 7 12]
 [ 8 65]
 [24 75]
 [58 84]
 [69 85]]
