# 09 Exercises: Broadcasting
**Note**: If any exercises require techniques we haven't covered yet - you should look this up! It's part of the learning process, we need to build the muscle of learning how to do things we haven't seen before.

Don't be shy, ask for help on Discord!

For each exercise, print the shapes of the arrays involved and the result of the operation to check your understanding of broadcasting rules.


1. Create a 1D NumPy array with 5 elements and add a scalar value to it.


In [1]:
import numpy as np

In [3]:
arr1 = np.arange(1, 6).reshape(5)
result = arr1 + 10 
print(f"Original array:\n{arr1}\n\nAfter adding scalar:\n{result}")

Original array:
[1 2 3 4 5]

After adding scalar:
[11 12 13 14 15]



2. Create a 2D NumPy array with dimensions 3x4 and subtract a 1D array with 4 elements from each row of the 2D array.


In [6]:
arr1 = np.arange(1, 13).reshape(3, 4)
arr2 = np.arange(0, 4)
result = arr1 - arr2
print(f"First array:\n{arr1}\n\nSecond array:\n{arr2}\n\nResult:\n{result}")

First array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Second array:
[0 1 2 3]

Result:
[[1 1 1 1]
 [5 5 5 5]
 [9 9 9 9]]



3. Create a 2D NumPy array with dimensions 4x3 and multiply it by a 1D array with 3 elements.


In [11]:
arr1 = np.arange(1, 13).reshape(4, 3)
arr2 = np.full(3, 2)
result = arr1 * arr2
print(f"First array:\n{arr1}\n\nSecond array:\n{arr2}\n\nResult:\n{result}")

First array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Second array:
[2 2 2]

Result:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]



4. Create a 3D NumPy array with dimensions 2x3x4 and add a 2D array with dimensions 3x4 to each 2D slice of the 3D array.


In [13]:
arr1 = np.arange(1, 25).reshape(2, 3, 4)
arr2 = np.full((3, 4) , 2)
result = arr1 * arr2
print(f"First array:\n{arr1}\n\nSecond array:\n{arr2}\n\nResult:\n{result}")

First array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Second array:
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]

Result:
[[[ 2  4  6  8]
  [10 12 14 16]
  [18 20 22 24]]

 [[26 28 30 32]
  [34 36 38 40]
  [42 44 46 48]]]



5. Create a 2D NumPy array with dimensions 5x2 and divide it by a 2D array with dimensions 1x2.


In [15]:
arr1 = np.random.randint(1,101, size =(5, 2))
arr2 = np.full((1,2), 2)
result = arr1 / arr2
print(f"First array:\n{arr1}\n\nSecond array:\n{arr2}\n\nResult:\n{result}")

First array:
[[70 98]
 [14 12]
 [66 78]
 [98 56]
 [13 35]]

Second array:
[[2 2]]

Result:
[[35.  49. ]
 [ 7.   6. ]
 [33.  39. ]
 [49.  28. ]
 [ 6.5 17.5]]



6. Create a 2D NumPy array with dimensions 3x3 and add a 1D array with 3 elements to each column of the 2D array.


In [31]:
arr1 = np.arange(1, 10).reshape(3, 3)
arr2 = np.arange(2, 5).reshape(3)
result = arr1 + arr2.reshape(3, 1)
print(f"First array:\n{arr1}\n\nSecond array:\n{arr2}\n\nResult:\n{result}")

First array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Second array:
[2 3 4]

Result:
[[ 3  4  5]
 [ 7  8  9]
 [11 12 13]]



7. Create a 3D NumPy array with dimensions 4x2x3 and multiply it by a 3D array with dimensions 1x2x3.


In [27]:
arr1 = np.random.randint(1, 101, size = (4, 2, 3))
arr2 = np.arange(5, 11).reshape(1, 2, 3)
result = arr1 * arr2
print(f"First array:\n{arr1}\n\nSecond array:\n{arr2}\n\nResult:\n{result}")

First array:
[[[59  2 63]
  [ 1 23 17]]

 [[93 19 56]
  [32 28 16]]

 [[90 14 18]
  [31 49 77]]

 [[34  9 30]
  [64 98 40]]]

Second array:
[[[ 5  6  7]
  [ 8  9 10]]]

Result:
[[[295  12 441]
  [  8 207 170]]

 [[465 114 392]
  [256 252 160]]

 [[450  84 126]
  [248 441 770]]

 [[170  54 210]
  [512 882 400]]]



8. Create a 2D NumPy array with dimensions 4x4 and subtract a scalar value from each element of the array.


In [29]:
arr1 = np.arange(10, 26).reshape(4, 4)
result = arr1 - 3
print(f"Original array:\n{arr1}\n\nResult:\n{result}")

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]

Result:
[[ 7  8  9 10]
 [11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]



9. Create a 3D NumPy array with dimensions 2x2x3 and divide it by a 2D array with dimensions 1x3.


In [30]:
arr1 = np.arange(1, 13).reshape(2, 2, 3)
arr2 = np.full((1, 3), 3)
result = arr1 / arr2
print(f"First array:\n{arr1}\n\nSecond array:\n{arr2}\n\nResult:\n{result}")

First array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Second array:
[[3 3 3]]

Result:
[[[0.33333333 0.66666667 1.        ]
  [1.33333333 1.66666667 2.        ]]

 [[2.33333333 2.66666667 3.        ]
  [3.33333333 3.66666667 4.        ]]]



10. Create a 2D NumPy array with dimensions 3x5 and add a 1D array with 1 element to each row of the 2D array.


In [42]:
arr1 = np.random.randint(1, 20, size = (3, 5))
arr2 = np.arange(10, 15).reshape(5)
result = arr1 + arr2
print(f"First array:\n{arr1}\n\nSecond array:\n{arr2}\n\nResult:\n{result}")

First array:
[[ 6  2 10 12 15]
 [ 2  6  3  2  9]
 [ 4  4  4  8  2]]

Second array:
[10 11 12 13 14]

Result:
[[16 13 22 25 29]
 [12 17 15 15 23]
 [14 15 16 21 16]]



11. Create a 3D NumPy array with dimensions 2x4x3 and subtract a 2D array with dimensions 4x1 from each 3D slice of the 3D array.


In [46]:
arr1 = np.arange(20, 44).reshape(2, 4, 3)
arr2 = np.arange(2, 6).reshape(4, 1)
result = arr1 - arr2
print(f"First array:\n{arr1}\n\nSecond array:\n{arr2}\n\nResult:\n{result}")

First array:
[[[20 21 22]
  [23 24 25]
  [26 27 28]
  [29 30 31]]

 [[32 33 34]
  [35 36 37]
  [38 39 40]
  [41 42 43]]]

Second array:
[[2]
 [3]
 [4]
 [5]]

Result:
[[[18 19 20]
  [20 21 22]
  [22 23 24]
  [24 25 26]]

 [[30 31 32]
  [32 33 34]
  [34 35 36]
  [36 37 38]]]



12. Create a 2D NumPy array with dimensions 4x2 and multiply it by a 2D array with dimensions 4x1.


In [47]:
arr1 = np.arange(1, 9).reshape(4, 2)
arr2 = np.arange(2,6).reshape(4, 1)
result = arr1 * arr2
print(f"First array:\n{arr1}\n\nSecond array:\n{arr2}\n\nResult:\n{result}")

First array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Second array:
[[2]
 [3]
 [4]
 [5]]

Result:
[[ 2  4]
 [ 9 12]
 [20 24]
 [35 40]]



13. Create a 3D NumPy array with dimensions 3x2x4 and add a 3D array with dimensions 3x1x1 to it.


In [50]:
arr1 = np.arange(1, 25).reshape(3, 2, 4)
arr2 = np.arange(25, 28).reshape(3, 1, 1)
result = arr1 + arr2
print(f"First array:\n{arr1}\n\nSecond array:\n{arr2}\n\nResult:\n{result}")

First array:
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]

Second array:
[[[25]]

 [[26]]

 [[27]]]

Result:
[[[26 27 28 29]
  [30 31 32 33]]

 [[35 36 37 38]
  [39 40 41 42]]

 [[44 45 46 47]
  [48 49 50 51]]]



14. Create a 2D NumPy array with dimensions 5x3 and divide it by a 1D array with 1 element.


In [65]:
arr1 = np.arange(15, 30).reshape(5, 3)
arr2 = np.array([10])
result = arr1 / arr2
print(f"First array:\n{arr1}\n\nSecond array:\n{arr2}\n\nResult:\n{result}")

First array:
[[15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]

Second array:
[10]

Result:
[[1.5 1.6 1.7]
 [1.8 1.9 2. ]
 [2.1 2.2 2.3]
 [2.4 2.5 2.6]
 [2.7 2.8 2.9]]



15. Create a 3D NumPy array with dimensions 2x3x4 and multiply it by a 3D array with dimensions 2x3x1.



In [70]:
arr1 = np.arange(1, 25).reshape(2, 3, 4)
arr2 = np.arange(2,8).reshape(2, 3, 1)
result = arr1 * arr2
print(f"First array:\n{arr1}\n\nSecond array:\n{arr2}\n\nResult:\n{result}")

First array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Second array:
[[[2]
  [3]
  [4]]

 [[5]
  [6]
  [7]]]

Result:
[[[  2   4   6   8]
  [ 15  18  21  24]
  [ 36  40  44  48]]

 [[ 65  70  75  80]
  [102 108 114 120]
  [147 154 161 168]]]
