# 09 Exercises: Random Module

**Note**: If any exercises require techniques we haven't covered yet - you should look this up! It's part of the learning process, we need to build the muscle of learning how to do things we haven't seen before.

Don't be shy, ask for help on Discord!

Remember to print the results of each exercise to verify your understanding of the random functions and their parameters.

In [1]:
import numpy as np

1. Generate a 1D array with 10 random floats between 0 and 1 using `np.random.random_sample()`.


In [17]:
arr1 = np.random.random_sample(10)
print(arr1)

[0.46574612 0.52012263 0.08823603 0.64731154 0.76238344 0.10351907
 0.15767305 0.76893649 0.33131695 0.04975399]



2. Generate a 2D array with shape (3, 4) containing random floats between 2 and 10 using `np.random.uniform()`.


In [15]:
arr1 = np.random.uniform(2, 10, size = (3, 4))
print(arr1)

[[6.58448328 6.64850867 5.75487262 7.60788881]
 [4.56100018 6.62166137 4.31531988 2.21498178]
 [5.34509763 7.65147508 2.43294709 8.02992247]]



3. Generate a 1D array with 5 random integers between 1 and 100 (inclusive) using `np.random.randint()`.


In [8]:
arr1 = np.random.randint(1, 101, size = 5)
print(arr1)

[61  9 49 96 17]



4. Generate a 2D array with shape (2, 5) containing random integers between -10 and 10 (inclusive) using `np.random.randint()`.



In [21]:
arr1 = np.random.randint(-10, 11, size = (2, 5))
print(arr1)

[[ -2 -10   9   4   6]
 [ 10   0   0   7  -2]]


5. Set a random seed to 42 using `np.random.seed()` and generate a random float using `np.random.uniform()`. Repeat this process and verify that you get the same random float.


In [32]:
np.random.seed(42)
arr1 = np.random.uniform()
print("First run:", arr1)
np.random.seed(42)
arr2 = np.random.uniform()
print("Second run:", arr2)
print("Are they equal?", arr1 == arr2)

First run: 0.3745401188473625
Second run: 0.3745401188473625
Are they equal? True



6. Generate a 1D array with 6 random floats from a standard normal distribution (mean=0, std=1) using `np.random.standard_normal()`.


In [40]:
arr1 = np.random.standard_normal(6)
print(arr1)

[ 0.21863832  0.88176104 -1.00908534 -1.58329421  0.77370042 -0.53814166]



7. Generate a 2D array with shape (4, 3) containing random floats from a normal distribution with mean=5 and std=2 using `np.random.normal()`.


In [43]:
arr1 = np.random.normal(loc = 5, scale = 2, size = (4, 3))
print(arr1)

[[11.74459251  3.15921839  4.20272322]
 [ 4.87827183  2.16249908  7.08498323]
 [ 6.80706498  5.03800066  3.93116709]
 [ 2.00989226  3.42148334  6.48742257]]



8. Create a list of 5 colors and use `np.random.choice()` to randomly select 3 colors from the list with equal probability.


In [65]:
colors = ["black", "red", "purple", "blue", "green"]
selected = np.random.choice(colors, size = 3, replace = False)
print(selected)

['black' 'red' 'green']



9. From the same list of colors, randomly select 4 colors with replacement and equal probability using `np.random.choice()`.


In [66]:
selected = np.random.choice(colors, size = 4, replace = True)
print(selected)

['purple' 'black' 'green' 'blue']



10. From the same list of colors, randomly select 2 colors without replacement and with specified probabilities using `np.random.choice()`.


In [75]:
probs = [0.10, 0.10, 0.7, 0.05, 0.05]
selected = np.random.choice(colors, size = 2, replace = False, p = probs)
print(selected)

['purple' 'black']



11. Create a `np.random.Generator` object with a seed of 123 and use it to generate a 1D array with 5 random floats between 0 and 1.


In [76]:
rng = np.random.default_rng(123)
arr1 = rng.random(5)
print(arr1)

[0.68235186 0.05382102 0.22035987 0.18437181 0.1759059 ]



12. Using the same `np.random.Generator` object, generate a 2D array with shape (2, 3) containing random integers between 1 and 20 (inclusive).


In [81]:
arr1 = rng.integers(1, 21, size = (2, 3))
print(arr1)

[[15  5 17]
 [16  5 11]]



13. Using the same `np.random.Generator` object, generate a 1D array with 4 random floats from a normal distribution with mean=10 and std=3.


In [82]:
arr = rng.normal(loc = 10, scale = 3, size = 4)

print(arr)

[ 3.37758671 12.48376432 14.62489118 13.38042038]



14. Create a list of 6 fruits and use the `np.random.Generator` object to randomly select 2 fruits from the list without replacement and with equal probability.


In [90]:
fruits = ["banana", "pineapple", "cherry", "grape", "orange", "melon"]
selected = rng.choice(fruits, size=2, replace=False)
print(selected)

['melon' 'grape']



15. Using the same list of fruits, use the `np.random.Generator` object to randomly select 5 fruits with replacement and specified probabilities.



In [97]:
probs = [0.2, 0.1, 0.1, 0.1, 0.2, 0.3]
selected = rng.choice(fruits, size = 5, replace = True, p = probs)
print(selected)

['melon' 'orange' 'grape' 'cherry' 'banana']
